*** Variables ***
${NAV_RSS_LPL}                                //span[normalize-space()='Requisition Self Service LPL']
${NAV_SHOPPING_HOME}                         //span[normalize-space()='Shopping Home']
${START_REQUISITION_HEADER}                  //h2[@id='RequesterSelfServiceHomePage_Dashboard_1_StartRequisitions2_widget_title']
${SHOP_PUNCHOUT_VENDORS_BTN}                 //span[normalize-space()='Shop Punchout Vendors']
${SHOP_PUNCHOUT_VENDORS_HEADER}              //span[@id='RequesterShoppingPage_ShopPunchoutVendors_3_RSSLPLShopPunchoutVendorsList_toolbar_toolbar_title']