*** Variables ***
#**********Tenant URL's**********
${D830RCA_AX1}  https://mingle-cqa-portal.cqa.inforcloudsuite.com/v2/D830RCA_AX1/

#**********LOGIN USERNAME**********
${USER100}  5000100
${USER99}  500099
#**********LOGIN PASSWORD**********
${USERPASS}    N0R3gr3ss1on!_MT

#**********TIMEOUT**********
${SLOW}	0.5
${SLOW_0_2}	0.2
${REMOVE_SLOW}	0
${RETRY}	10
${INTERVAL}	2
${DELAY}	10
${MaximumTimeout}	30
${StandardTimeout}	10
#**********RETRY**********
${Three}    3